name: 'Scoverage Pull Request Comment'
description: ''
inputs:
  github-token:
    description: 'github token'
    default: ${{ github.token }}
  pull-request-number:
    description: 'pull request number'
  base-ref:
    description: 'base ref'
  head-ref:
    description: 'base ref'
  report-path:
    description: 'path to scoverage.xml'
    default: 'target/scala-2.13/scoverage-report/scoverage.xml'
runs:
  using: 'node16'
  main: 'dist/index.js'
