
name: Test
on:
  push:
    branches-ignore:
    - test
    - test2
jobs:
  test-action:
    name: Test action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: airfocusio/github-action-scoverage-pull-request-comment@main
      with:
        base-ref: test
        head-ref: test2
        pull-request-number: '1'
        report-path: test/scoverage.xml
